parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $publicDir: '%kernel.project_dir%/public'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
